if [ -f ~/.zshrc_local_before ]; then
    source ~/.zshrc_local_before
fi

# External plugins
source ~/.zsh/plugins.zsh

# Settings
source ~/.zsh/settings.zsh

# Bootstrap
#source ~/.zsh/bootstrap.zsh

# Aliases
source ~/.zsh/aliases.zsh

if [ -f ~/.zshrc_local_after ]; then
    source ~/.zshrc_local_after
fi

