echo "config bashrc"

# allow local customizations in the ~/.bashrc_local_before file
if [ -f ~/.bash_local/bashrc_local_before.bash ]; then
    source ~/.bash_local/bashrc_local_before.bash
fi

# settings
source ~/.bash/settings.bash

# bootstrap
source ~/.zsh/bootstrap.zsh

# aliases (share the same aliases with zsh)
source ~/.zsh/aliases.zsh

# allow local customizations in the ~/.bashrc_local_after file
if [ -f ~/.bash_local/bashrc_local_after.bash ]; then
    source ~/.bash_local/bashrc_local_after.bash
fi


